create table int_same_text_nocompress(x INT);
create table int_diff_text_nocompress(x INT);
create table int_increm_text_nocompress(x INT);
create table double_same_text_nocompress(x DOUBLE);
create table double_diff_text_nocompress(x DOUBLE);
create table double_increm_text_nocompress(x DOUBLE);
create table boolean_same_text_nocompress(x BOOLEAN);
create table boolean_diff_text_nocompress(x BOOLEAN);
create table boolean_increm_text_nocompress(x BOOLEAN);
create table string_same_text_nocompress(x STRING);
create table string_diff_text_nocompress(x STRING);
create table string_increm_text_nocompress(x STRING);
create table timestamp_same_text_nocompress(x TIMESTAMP);
create table timestamp_diff_text_nocompress(x TIMESTAMP);
create table timestamp_increm_text_nocompress(x TIMESTAMP);

set compression_codec=none;
insert into int_same_text_nocompress select * from int_same_text;
insert into int_diff_text_nocompress select * from int_diff_text;
insert into int_increm_text_nocompress select * from int_increm_text;
insert into double_same_text_nocompress select * from double_same_text;
insert into double_diff_text_nocompress select * from double_diff_text;
insert into double_increm_text_nocompress select * from double_increm_text;
insert into boolean_same_text_nocompress select * from boolean_same_text;
insert into boolean_diff_text_nocompress select * from boolean_diff_text;
insert into boolean_increm_text_nocompress select * from boolean_increm_text;
insert into string_same_text_nocompress select * from string_same_text;
insert into string_diff_text_nocompress select * from string_diff_text;
insert into string_increm_text_nocompress select * from string_increm_text;
insert into timestamp_same_text_nocompress select * from timestamp_same_text;
insert into timestamp_diff_text_nocompress select * from timestamp_diff_text;
insert into timestamp_increm_text_nocompress select * from timestamp_increm_text;
